spring.application.name=ToDomangemnet
spring.datasource.url=jdbc:mysql://localhost:3306/ToDoSystem
spring.datasource.username=ToDoUser
spring.datasource.password=3245678hjhghgfrrss
spring.jpa.hibernate.ddl-auto=update
